#!/bin/bash

function run() {
  echo "$@"
  $@
}

function format_hs() {
  # Adapted from https://prettier.io/docs/en/precommit.html
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.hs" | sed 's| |\\ |g')
  [ -z "$FILES" ] && return 0

  which ormolu
  [[ "$?" == "0" ]] || { echo "ormolu not found. Please install it to automatically format files"; return 0; }

  # Format all selected files
  echo "$FILES" | xargs ormolu --mode inplace

  # Add back the modified files to staging
  echo "$FILES" | xargs git add

  return 0
}

set -e

if [[ -z "$ZZ_HOME" && ! -e "zzbot" ]]; then
  echo "Either the zzbot executable must be in `pwd` or ZZ_HOME must be specified"
  echo "zzbot is available at https://github.com/smelc/zzbot"
  exit 1
fi

if [[ ! -z "$ZZ_HOME" ]]
then
  # zzbot's repository is locally available, update it
  declare -r HERE=`pwd`
  run cd $ZZ_HOME
  run stack build
  run stack install zzbot --local-bin-path $HERE
  run cd -
fi
run ./zzbot test/zzbot.xml

format_hs
