name:                scripts
dependencies:
    - base
    - extra
    - filepath
    - process

executables:
  genassets:
    main:            GenAssets.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
